### ISSUE TITLE
GTTBooster 7.176 - LQE tool - Revert to pass tip not showing

### ISSUE THREAD

**Issue by XavierNovella** [EirikBirkeland/gttbooster#80]
When LQE is opened and GTT booster is on, formerly we could see a little tip advising how many errors shoudl be reverted to get the job to be a pass (or just stating that the job was not a fail.

I hope you can fix it as this appeared with an update you did recently.

**Comment by EirikBirkeland** [comment]
Hi Xavier,

I decided to remove this because Google may not like us using it (someone
at Google actually expressed concern, but this was several years ago).

But actually, I've just restored the feature :) So you'll be seeing it now
;)

Best regards,
Eirik Birkeland
Independent Translation Tool Developer
<https://www.linkedin.com/in/eirikbirkeland/>


Den fre. 19. okt. 2018 kl. 11:28 skrev XavierNovella <
notifications@github.com>:

**Comment by XavierNovella** [comment]
awesome!

Xavier Novella Sinde
<http://de.linkedin.com/pub/xavier-novella-sinde/41/2b3/884/en>
Translator and localizer EN, DE, JP to ES, CA
 +34627368091 (Spanish)




Missatge de Eirik Birkeland <notifications@github.com> del dia dv., 19
d’oct. 2018 a les 13:04:
